name: Generate derived files

on:
  push:
    branches:
      - main
      - edge

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: andrewjstryker/makefile-helper
          token: ${{ PRIVATE_TOKEN_GITHUB }}

      - name: Generate files
        run: |
          make all

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - code generator"
          git add --all
          git commit -m "Update derived files" || echo "No changes to commit"
          git push
